#!/usr/bin/env python3
"""Build immutable Template Generation prompt constants and protocol metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

TEMPLATE_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = TEMPLATE_ROOT / "resources/source"
GENERATED_ROOT = TEMPLATE_ROOT / "engine/cardplan/generated"
PROMPT_GROUPS = {
    "selection": (
        "card-plan-template-prompt/0.3",
        "card-plan-template/0.2",
        "card-template-planner",
    ),
    "body": (
        "hybrid-body-prompt/0.25",
        "tersedsl-nested-2-hybrid/0.2",
        "hybrid-body-generator",
    ),
    "ux_mixed": (
        "ux-mixed-prompt/0.15",
        "tersedsl-nested-2-ux-mixed/0.5",
        "ux-mixed-generator",
    ),
}


def _python_string_literal(value: str, width: int = 40) -> str:
    """Render a value as adjacent bounded Python string literals."""
    chunks: list[str] = []
    current = ""
    for character in value:
        candidate = current + character
        if current and len(repr(candidate)) > width:
            chunks.append(current)
            current = character
        else:
            current = candidate
    if current or not chunks:
        chunks.append(current)
    lines = ["("]
    lines.extend(f"    {chunk!r}" for chunk in chunks)
    lines.append(")")
    return "\n".join(lines)


def _prompt_body(path: Path) -> tuple[int, str]:
    text = path.read_text(encoding="utf-8")
    try:
        front_matter, remainder = text.split("---", 2)[1:]
        order_line = next(line for line in front_matter.splitlines() if line.startswith("order:"))
        start = remainder.index("<!-- prompt:start -->") + len("<!-- prompt:start -->")
        end = remainder.index("<!-- prompt:end -->")
    except (IndexError, StopIteration, ValueError) as exc:
        raise ValueError(f"invalid prompt fragment: {path}") from exc
    return int(order_line.split(":", 1)[1].strip()), remainder[start:end].strip()


def _build() -> tuple[str, str]:
    prompt_values: dict[str, str] = {}
    for key, (_prompt_version, _protocol_version, directory) in PROMPT_GROUPS.items():
        fragments = sorted(
            (_prompt_body(path) for path in (SOURCE_ROOT / "prompts" / directory).glob("*.md")),
            key=lambda item: item[0],
        )
        prompt = "\n\n".join(body for _order, body in fragments)
        prompt_values[key] = prompt

    manifest = {
        "bundleVersion": "cardplan-template-python-bundle/1",
        "selectionProtocolVersion": PROMPT_GROUPS["selection"][1],
        "bodyProtocolVersion": PROMPT_GROUPS["body"][1],
        "uxMixedProtocolVersion": PROMPT_GROUPS["ux_mixed"][1],
        "contractVersion": "hybrid-body-contract/0.5",
        "providerBundleVersion": "card-provider-bundle/1",
        "themeBaseVersion": "theme-base/2",
        "themeBundleVersion": "card-theme/2",
        "a2uiWireVersion": "v0.9",
        "a2uiTargetSpecVersion": "v0.9.1",
        "catalogId": "ohos.a2ui.extended.catalog.form",
    }
    manifest_text = json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    prompts_text = (
        '"""Generated by template_generation/tools/build_cardplan_bundle.py; do not edit."""\n\n'
        f"SELECTION_PROMPT_VERSION = {PROMPT_GROUPS['selection'][0]!r}\n"
        f"SELECTION_PROTOCOL_VERSION = {PROMPT_GROUPS['selection'][1]!r}\n"
        f"SELECTION_SYSTEM_PROMPT = {_python_string_literal(prompt_values['selection'])}\n\n"
        f"BODY_PROMPT_VERSION = {PROMPT_GROUPS['body'][0]!r}\n"
        f"BODY_PROTOCOL_VERSION = {PROMPT_GROUPS['body'][1]!r}\n"
        'BODY_CONTRACT_VERSION = "hybrid-body-contract/0.5"\n'
        f"BODY_SYSTEM_PROMPT_KERNEL = {_python_string_literal(prompt_values['body'])}\n"
        f"\nUX_MIXED_PROMPT_VERSION = {PROMPT_GROUPS['ux_mixed'][0]!r}\n"
        f"UX_MIXED_PROTOCOL_VERSION = {PROMPT_GROUPS['ux_mixed'][1]!r}\n"
        f"UX_MIXED_SYSTEM_PROMPT_KERNEL = {_python_string_literal(prompt_values['ux_mixed'])}\n"
    )
    return manifest_text, prompts_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest_text, prompts_text = _build()
    outputs = {
        GENERATED_ROOT / "prompt-manifest.json": manifest_text,
        GENERATED_ROOT / "prompts.py": prompts_text,
    }
    if args.check:
        drifted = [
            path
            for path, content in outputs.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != content
        ]
        if drifted:
            raise SystemExit("CardPlan bundle drift: " + ", ".join(map(str, drifted)))
        return 0
    GENERATED_ROOT.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
